apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scalable-app
  template:
    metadata:
      labels:
        app: scalable-app
    spec:
      containers:
      - name: scalable-app
        image: scalable-app:v3
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "64Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 2
          periodSeconds: 5